python-djangogram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    # path("users/", include("djangogram.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    #  /
    path("", include("djangogram.users.urls", namespace="users")),

    # /posts/
     path("posts/", include("djangogram.posts.urls", namespace="posts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

python-djangogram/djangogram/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
]

python-djangogram/djangogram/users/urls.py
from django.urls import path
from . import views
    


app_name = "users"
urlpatterns = [
    path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
]

python-djangogram/djangogram/posts/models.py
from django.db import models
from djangogram.users import models as user_model

# Create your models here.
class TimeStampedModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True
class post(TimeStampedModel):
    author = models.ForeignKey(
                user_model.User,
                null=True,
                on_delete=models.CASCADE,
                related_name= 'post_author'
            )
    image = models.ImageField(blank=True)
    caption = models.TextField(blank=True)
    image_likes = models.ManyToManyField(
                    user_model.User,
                    related_name='post_image_likes'
            )

class Comment(TimeStampedModel):
    author = models.ForeignKey(
                user_model.User,
                null=True,
                on_delete=models.CASCADE,
                related_name= 'comment_author'
            )
    posts = models.ForeignKey(
                post,
                null=True,
                on_delete=models.CASCADE,
                related_name= 'comment_post'
            )
    contents = models.TextField(blank=True)

python-djangogram/djangogram/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('C', 'Custom'),
    ]



    """Default user for djangogram."""

    #: First and last name do not cover name patterns around the globe
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    user_name = models.CharField(blank=True, max_length=255)
    profile_photo = models.ImageField(blank=True)
    website = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    email = models.CharField(blank=True, max_length=255)
    phone_number = models.CharField(blank=True, max_length=255)
    gender = models.CharField(blank=True, choices=GENDER_CHOICES, max_length=255)
    followers = models.ManyToManyField("self")
    following = models.ManyToManyField("self")

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

python-djangogram/djangogram/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms as django_forms
User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

class SignUpForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'name', 'username', 'password']

        # labels = {
        #     'email' : '이메일 주소',
        #     'name' : '성명',
        #     'username' : '사용자 이름',
        #     'password' :  '비밀번호',

        # }

        widgets = {
            'email': django_forms.TextInput(attrs={'placeholder': '이메일 주소'}),
            'name': django_forms.TextInput(attrs={'placeholder': '성명'}),
            'username': django_forms.TextInput(attrs={'placeholder': '사용자 이름'}),
            'password': django_forms.PasswordInput(attrs={'placeholder': '비밀번호'}),




        }

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

python-djangogram/djangogram/posts/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'posts/base.html')

python-djangogram/djangogram/users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import SignUpForm

def main(request):
    if request.method == 'GET':
        return render(request, 'users\main.html')
    # 장고 문서 내에 존재하는 장고 로그인폼 사용  겟방식과 포스트 분기 코드 작성
    elif request.method == 'POST':  
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                # Redirect to a success page.
                return HttpResponseRedirect(reverse('posts:index'))

            else:
                # Return an 'invalid login' error message.
                return render(request, 'users\main.html')
# 장고폼사용 회원가입 로직 
def signup(request):
    if request.method == 'GET':
        form = SignUpForm()

        return render(request, 'users/signup.html', {'form' : form})

    elif request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
#자동로그인 성공하면 cleaned 데이터에 저장됨
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                # Redirect to a success page.
                return HttpResponseRedirect(reverse('posts:index'))

            else:
                # Return an 'invalid login' error message.
                return render(request, 'users\main.html')

        return render(request, 'users/main.html')

python-djangogram/djangogram/templates/pages/about.html
{% extends "base.html" %}

python-djangogram/djangogram/templates/pages/home.html
{% extends "base.html" %}

python-djangogram/djangogram/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" type="text/css" href="{% static 'css/users/main.css'%}">
    <title>{% block title %}{% endblock %}-Djangogram</title>
</head>
<body>
    <div class="content">
        {% block content %} {% endblock %}
    </div>

    {% include "users/footer.html" %}
</body>
</html>

python-djangogram/djangogram/templates/users/footer.html
<footer>
    <div class="list">
        <ul>
            <li><a href = "#">소개</a></li>
            <li><a href = "#">도움말</a></li>
            <li><a href = "#">홍보 센터</a></li>
            <li><a href = "#">API</a></li>
            <li><a href = "#">채용정보</a></li>
        </ul>
    </div>
    <div class="company">
        2020 Djangogram from 정간지
    </div>
</footer> 

python-djangogram/djangogram/templates/users/main.html
{% extends "users/base.html" %}

{% block title%}
Log in
{% endblock title%}
Here is main.html.

{% block content %}
<div class="auth">
    <form action="{% url 'users:main' %}" method='post'>
        {% csrf_token %}
        <input type="input" name="username" placeholder="username">
        <input type="password" name="password" placeholder="password">
        <input type="submit" value="Login">
    </form>
</div>

<div class="auth_link">
    <a href="{% url 'users:signup' %}">Sign up</a>
</div>


{% endblock content %}

python-djangogram/djangogram/templates/users/signup.html
{% extends "users/base.html" %}

<h1>Here is SignUp page</h1>
{% block title %}
sign up
{% endblock title %}


{% block content %}
<div class="auth">
    <form action="{% url 'users:signup'%}" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field }}
        </div>
        {% endfor %}
        <input type="submit" value="Sign up">

    </form>
</div>
<div class="auth_link">
    <a href="{% url 'users:main' %}">Login</a>
</div>
{% endblock content %}

python-djangogram/djangogram/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

python-djangogram/djangogram/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}